### ISSUE TITLE
Documentation: Outdated versions/image information

### ISSUE THREAD

**Issue by voetberg** [mapsacosta/EAFJupyter#21]
Current documentation says the default image is SL7, which is no longer true. Both the readthedocs page and the [diagram page](https://eafjupyter.readthedocs.io/en/latest/01_diagram.html) need to be updated. While this is getting updated, it would also be useful to have the default python version listed (iirc it was just changed form 3.9 to 3.10, though I cannot find where this announced for the life of me). 

Idea for the future - it would be useful to have these changes announced through email listed on the readthedocs page

**Comment by holzman** [comment]
Solved by #27
